create table country
(
    id        BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name      varchar(255),
    continent varchar(255)
);
create table host
(
    id         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name       varchar(255),
    surname    varchar(255),
    country_id BIGINT REFERENCES country ON DELETE CASCADE
);
create table accommodation
(
    id           BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name         varchar(255),
    category     varchar(50),
    host_id      BIGINT REFERENCES host ON DELETE CASCADE,
    is_available BOOLEAN
);
CREATE table shop_users
(
    username                   VARCHAR(255) PRIMARY KEY,
    password                   VARCHAR(255),
    name                       VARCHAR(255),
    surname                    VARCHAR(255),
    is_account_non_expired     BOOLEAN DEFAULT TRUE,
    is_account_non_locked      BOOLEAN DEFAULT TRUE,
    is_credentials_non_expired BOOLEAN DEFAULT TRUE,
    is_enabled                 BOOLEAN DEFAULT TRUE,
    role                       VARCHAR(50)
);
create table reservation_list
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_username varchar(255) references shop_users on delete cascade,
    status        varchar(50)

);
create table reservation_item
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    accommodation BIGINT REFERENCES accommodation ON delete cascade,
    num_rooms     INTEGER

);
create table reservations_list_items
(
    reservation_list_id BIGINT REFERENCES reservation_list on delete cascade,
    items_id     BIGINT references reservation_item on delete cascade,
    primary key (reservation_list_id, items_id)
);